ALTER TABLE series ADD COLUMN revision INTEGER NOT NULL DEFAULT 1;
ALTER TABLE movies ADD COLUMN revision INTEGER NOT NULL DEFAULT 1;
ALTER TABLE downloads ADD COLUMN revision INTEGER NOT NULL DEFAULT 1;
