[package]
name = "yokoku-system"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
yokoku-detect.workspace = true
yokoku-domain.workspace = true
yokoku-events.workspace = true
yokoku-media.workspace = true

async-trait.workspace = true
jiff = { workspace = true, features = ["serde"] }
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["fs", "process", "rt", "time"] }
tracing.workspace = true

walkdir = "2.5"

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["rt", "macros", "sync", "time"] }
