[package]
name = "yokoku-media"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
yokoku-detect.workspace = true
yokoku-domain.workspace = true
yokoku-events.workspace = true
yokoku-naming.workspace = true

async-trait.workspace = true
jiff.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
yokoku-db.workspace = true
yokoku-library.workspace = true
yokoku-system.workspace = true
yokoku-test-support.workspace = true

rstest.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["rt", "macros"] }
