[package]
name = "yokoku-config"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
yokoku-core.workspace = true
yokoku-domain.workspace = true
yokoku-infra.workspace = true
yokoku-jobs.workspace = true

anyhow.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true

config = { version = "0.15", default-features = false, features = ["json", "toml"] }

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["rt", "macros"] }
