[package]
name = "yokoku-download-clients"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
yokoku-domain.workspace = true
yokoku-downloads.workspace = true

async-trait.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true

base64 = "0.22"

[dev-dependencies]
yokoku-db.workspace = true
yokoku-events.workspace = true
yokoku-system.workspace = true

jiff.workspace = true
rstest.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["rt", "macros", "process", "time"] }
wiremock.workspace = true
