[package]
name = "yokoku"
description = "TBD"
readme = "../../README.md"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[[bin]]
name = "yokoku"
path = "src/main.rs"

[features]
default = []
tokio-console = ["dep:console-subscriber"]

[dependencies]
yokoku-db.workspace = true
yokoku-detect.workspace = true
yokoku-domain.workspace = true
yokoku-downloads.workspace = true
yokoku-events.workspace = true
yokoku-jobs.workspace = true
yokoku-library.workspace = true
yokoku-media.workspace = true
yokoku-metadata.workspace = true
yokoku-naming.workspace = true
yokoku-system.workspace = true
yokoku-transmission.workspace = true

anyhow.workspace = true
clap.workspace = true
clap-verbosity-flag.workspace = true
config.workspace = true
console-subscriber = { workspace = true, optional = true }
jiff.workspace = true
jiff-cron.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal"] }
tokio-util.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
criterion.workspace = true
predicates.workspace = true
serde_json.workspace = true
tempfile.workspace = true
wiremock.workspace = true

[[bench]]
name = "benchmark"
harness = false

[lints]
workspace = true
