[package]
name = "yokoku-naming"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
yokoku-domain.workspace = true

serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
jiff.workspace = true
proptest.workspace = true
rstest.workspace = true
