[package]
name = "yokoku-metadata"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
yokoku-domain.workspace = true
yokoku-library.workspace = true

async-trait.workspace = true
isolang.workspace = true
jiff.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["sync", "time"] }
tracing.workspace = true

governor = { version = "0.10", default-features = false, features = ["std"] }

[dev-dependencies]
yokoku-test-support.workspace = true

rstest.workspace = true
tokio = { workspace = true, features = ["rt", "macros"] }
wiremock.workspace = true
