//! The settings the web's Settings page shows, with their labels, hints and controls.

use yokoku_web::{Control, Field, Section};

use crate::config::Config;

impl Config {
    /// The settings the web's Settings page shows, in page order.
    pub fn fields() -> Vec<Field> {
        vec![
            Field::new(
                Section::DownloadClient,
                "transmission.url",
                "Transmission address",
                "Its RPC address.",
                Control::text("http://localhost:9091/transmission/rpc"),
            ),
            Field::new(
                Section::DownloadClient,
                "transmission.username",
                "Username",
                "Empty when Transmission asks for none.",
                Control::text(""),
            ),
            Field::new(Section::DownloadClient, "transmission.password", "Password", "", Control::Secret),
            Field::new(
                Section::MediaServer,
                "jellyfin.url",
                "Jellyfin address",
                "Asked to rescan after imports; empty to not use Jellyfin.",
                Control::text("http://localhost:8096"),
            ),
            Field::new(
                Section::MediaServer,
                "jellyfin.api_key",
                "API key",
                "From Jellyfin's dashboard, under API keys.",
                Control::Secret,
            ),
            Field::new(
                Section::MediaServer,
                "jellyfin.user",
                "User",
                "Whose played items count as watched; empty to not sync watched files.",
                Control::text(""),
            ),
            Field::new(
                Section::Metadata,
                "metadata.tmdb.token",
                "TMDB token",
                "The API read access token; needed to search, add and refresh items.",
                Control::Secret,
            ),
            Field::new(
                Section::Metadata,
                "metadata.tvdb.api_key",
                "TVDB API key",
                "Series come from TVDB once it is set; use the source Jellyfin uses.",
                Control::Secret,
            ),
            Field::new(Section::Metadata, "metadata.tvdb.pin", "TVDB subscriber PIN", "", Control::Secret),
            Field::new(
                Section::Metadata,
                "metadata.language",
                "Language",
                "Titles and overviews.",
                Control::choice(LANGUAGES),
            ),
            Field::new(
                Section::Metadata,
                "metadata.region",
                "Region",
                "Whose movie release dates are shown.",
                Control::choice(REGIONS),
            ),
            Field::new(
                Section::Metadata,
                "metadata.tmdb.url",
                "TMDB address",
                "The API's address; change it only for a proxy or mirror.",
                Control::text("https://api.themoviedb.org/3"),
            ),
            Field::new(
                Section::Metadata,
                "metadata.tvdb.url",
                "TVDB address",
                "The API's address; change it only for a proxy or mirror.",
                Control::text("https://api4.thetvdb.com/v4"),
            ),
            Field::new(
                Section::Library,
                "add.monitor",
                "Monitor new series",
                "What a new series monitors at first; a new movie is monitored unless this is Nothing.",
                Control::choice(&[
                    ("all", "All episodes"),
                    ("future", "Future episodes"),
                    ("latest-season", "Latest season"),
                    ("none", "Nothing"),
                ]),
            ),
            Field::new(
                Section::Library,
                "clock.timezone",
                "Time zone",
                "For air dates, like Europe/Berlin; the server's own when empty.",
                Control::text(""),
            ),
            Field::new(
                Section::Import,
                "import.mode",
                "Import mode",
                "A hard link or copy lets the torrent keep seeding; a move does not.",
                Control::choice(&[("hardlink", "Hard link"), ("copy", "Copy"), ("move", "Move")]),
            ),
            Field::new(
                Section::Import,
                "downloads.remove_after_seeding",
                "Remove torrents after seeding",
                "Removes imported torrents with their data once Transmission finished seeding them.",
                Control::Switch,
            ),
            Field::new(
                Section::Import,
                "downloads.pick_up_labels",
                "Pick up labels",
                "Takes on torrents added in Transmission with one of these labels, comma-separated.",
                Control::List,
            ),
            Field::new(
                Section::Import,
                "downloads.pick_up_folder",
                "Pick up folder",
                "…or downloading under this folder.",
                Control::text(""),
            ),
            Field::new(Section::Naming, "naming.series_folder", "Series folder", "", Control::text("")),
            Field::new(Section::Naming, "naming.season_folder", "Season folder", "", Control::text("")),
            Field::new(Section::Naming, "naming.episode_file", "Episode file", "", Control::text("")),
            Field::new(Section::Naming, "naming.movie_folder", "Movie folder", "", Control::text("")),
            Field::new(Section::Naming, "naming.movie_file", "Movie file", "", Control::text("")),
            Field::new(
                Section::Files,
                "files.ffprobe",
                "ffprobe",
                "Reads file details: its name on the PATH, or a path to it.",
                Control::text("ffprobe"),
            ),
            Field::new(Section::Schedules, "serve.sync_downloads", "Sync downloads", "", Control::text("")),
            Field::new(
                Section::Schedules,
                "serve.sync_active_downloads",
                "Sync active downloads",
                "While a download is queued or downloading.",
                Control::text(""),
            ),
            Field::new(
                Section::Schedules,
                "serve.execute_imports",
                "Run imports",
                "Carries out approved imports.",
                Control::text(""),
            ),
            Field::new(
                Section::Schedules,
                "serve.rescan_media_server",
                "Jellyfin rescan",
                "Checks whether a rescan is due.",
                Control::text(""),
            ),
            Field::new(
                Section::Schedules,
                "serve.sync_watched",
                "Watched sync",
                "Mirrors the Jellyfin user's played items onto library files.",
                Control::text(""),
            ),
            Field::new(
                Section::Schedules,
                "serve.refresh_metadata",
                "Refresh metadata",
                "Refreshes only the items due for it.",
                Control::text(""),
            ),
            Field::new(
                Section::Schedules,
                "serve.scan_library",
                "Scan library",
                "Looks for files changed outside Yokoku in the root folders.",
                Control::text(""),
            ),
            Field::new(
                Section::Server,
                "database.path",
                "Database",
                "The SQLite file; artwork is kept in an artwork folder next to it.",
                Control::ReadOnly,
            ),
            Field::new(
                Section::Server,
                "web.host",
                "Listen address",
                "0.0.0.0 for every interface.",
                Control::ReadOnly,
            ),
            Field::new(Section::Server, "web.port", "Port", "", Control::ReadOnly),
            Field::new(
                Section::Server,
                "log.level",
                "Log level",
                "RUST_LOG or -v and -q go over it when given.",
                Control::ReadOnly,
            ),
            Field::new(Section::Server, "log.format", "Log format", "console or json.", Control::ReadOnly),
            Field::new(
                Section::Server,
                "log.output",
                "Log output",
                "stderr, stdout or { file = \"path\" }.",
                Control::ReadOnly,
            ),
            Field::new(
                Section::Server,
                "events.poll_interval_ms",
                "Event poll interval",
                "Milliseconds between checks for changes made from the command line.",
                Control::ReadOnly,
            ),
        ]
    }
}

/// TMDB's translations.
const LANGUAGES: &[(&str, &str)] = &[
    ("ar-SA", "Arabic · ar-SA"),
    ("bg-BG", "Bulgarian · bg-BG"),
    ("zh-CN", "Chinese, Simplified · zh-CN"),
    ("zh-TW", "Chinese, Traditional · zh-TW"),
    ("zh-HK", "Chinese, Hong Kong · zh-HK"),
    ("hr-HR", "Croatian · hr-HR"),
    ("cs-CZ", "Czech · cs-CZ"),
    ("da-DK", "Danish · da-DK"),
    ("nl-NL", "Dutch · nl-NL"),
    ("en-US", "English, US · en-US"),
    ("en-GB", "English, UK · en-GB"),
    ("en-AU", "English, Australia · en-AU"),
    ("en-CA", "English, Canada · en-CA"),
    ("fi-FI", "Finnish · fi-FI"),
    ("fr-FR", "French · fr-FR"),
    ("fr-CA", "French, Canada · fr-CA"),
    ("de-DE", "German · de-DE"),
    ("el-GR", "Greek · el-GR"),
    ("he-IL", "Hebrew · he-IL"),
    ("hi-IN", "Hindi · hi-IN"),
    ("hu-HU", "Hungarian · hu-HU"),
    ("id-ID", "Indonesian · id-ID"),
    ("it-IT", "Italian · it-IT"),
    ("ja-JP", "Japanese · ja-JP"),
    ("ko-KR", "Korean · ko-KR"),
    ("lt-LT", "Lithuanian · lt-LT"),
    ("lv-LV", "Latvian · lv-LV"),
    ("nb-NO", "Norwegian · nb-NO"),
    ("fa-IR", "Persian · fa-IR"),
    ("pl-PL", "Polish · pl-PL"),
    ("pt-BR", "Portuguese, Brazil · pt-BR"),
    ("pt-PT", "Portuguese, Portugal · pt-PT"),
    ("ro-RO", "Romanian · ro-RO"),
    ("ru-RU", "Russian · ru-RU"),
    ("sr-RS", "Serbian · sr-RS"),
    ("sk-SK", "Slovak · sk-SK"),
    ("sl-SI", "Slovenian · sl-SI"),
    ("es-ES", "Spanish, Spain · es-ES"),
    ("es-MX", "Spanish, Latin America · es-MX"),
    ("sv-SE", "Swedish · sv-SE"),
    ("th-TH", "Thai · th-TH"),
    ("tr-TR", "Turkish · tr-TR"),
    ("uk-UA", "Ukrainian · uk-UA"),
    ("vi-VN", "Vietnamese · vi-VN"),
];

/// Countries, by ISO 3166-1 code.
const REGIONS: &[(&str, &str)] = &[
    ("AR", "Argentina · AR"),
    ("AU", "Australia · AU"),
    ("AT", "Austria · AT"),
    ("BE", "Belgium · BE"),
    ("BR", "Brazil · BR"),
    ("BG", "Bulgaria · BG"),
    ("CA", "Canada · CA"),
    ("CL", "Chile · CL"),
    ("CN", "China · CN"),
    ("CO", "Colombia · CO"),
    ("HR", "Croatia · HR"),
    ("CZ", "Czechia · CZ"),
    ("DK", "Denmark · DK"),
    ("EG", "Egypt · EG"),
    ("EE", "Estonia · EE"),
    ("FI", "Finland · FI"),
    ("FR", "France · FR"),
    ("DE", "Germany · DE"),
    ("GR", "Greece · GR"),
    ("HK", "Hong Kong · HK"),
    ("HU", "Hungary · HU"),
    ("IS", "Iceland · IS"),
    ("IN", "India · IN"),
    ("ID", "Indonesia · ID"),
    ("IE", "Ireland · IE"),
    ("IL", "Israel · IL"),
    ("IT", "Italy · IT"),
    ("JP", "Japan · JP"),
    ("KZ", "Kazakhstan · KZ"),
    ("LV", "Latvia · LV"),
    ("LT", "Lithuania · LT"),
    ("MY", "Malaysia · MY"),
    ("MX", "Mexico · MX"),
    ("NL", "Netherlands · NL"),
    ("NZ", "New Zealand · NZ"),
    ("NG", "Nigeria · NG"),
    ("NO", "Norway · NO"),
    ("PE", "Peru · PE"),
    ("PH", "Philippines · PH"),
    ("PL", "Poland · PL"),
    ("PT", "Portugal · PT"),
    ("RO", "Romania · RO"),
    ("RU", "Russia · RU"),
    ("SA", "Saudi Arabia · SA"),
    ("RS", "Serbia · RS"),
    ("SG", "Singapore · SG"),
    ("SK", "Slovakia · SK"),
    ("SI", "Slovenia · SI"),
    ("ZA", "South Africa · ZA"),
    ("KR", "South Korea · KR"),
    ("ES", "Spain · ES"),
    ("SE", "Sweden · SE"),
    ("CH", "Switzerland · CH"),
    ("TW", "Taiwan · TW"),
    ("TH", "Thailand · TH"),
    ("TR", "Türkiye · TR"),
    ("UA", "Ukraine · UA"),
    ("AE", "United Arab Emirates · AE"),
    ("GB", "United Kingdom · GB"),
    ("US", "United States · US"),
    ("VN", "Vietnam · VN"),
];
