[package]
name = "yokoku-events"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
yokoku-domain.workspace = true

async-trait.workspace = true
jiff.workspace = true
tokio = { workspace = true, features = ["rt", "sync", "time", "macros"] }
tokio-util.workspace = true
tracing.workspace = true

[dev-dependencies]
yokoku-db.workspace = true

proptest.workspace = true
rstest.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["rt", "macros"] }
