[package]
name = "yokoku-jobs"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
yokoku-domain.workspace = true
yokoku-downloads.workspace = true
yokoku-events.workspace = true
yokoku-integrations.workspace = true
yokoku-library.workspace = true
yokoku-media.workspace = true

jiff.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt", "time", "macros"] }
tokio-util.workspace = true
tracing.workspace = true

jiff-cron = "0.3"

[dev-dependencies]
tracing-subscriber.workspace = true
