[package]
name = "yokoku-jobs"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
yokoku-downloads.workspace = true
yokoku-media.workspace = true

apalis.workspace = true
apalis-cron.workspace = true
jiff-cron.workspace = true
tracing.workspace = true
