[package]
name = "yokoku-jobs"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
yokoku-downloads.workspace = true
yokoku-events.workspace = true
yokoku-integrations.workspace = true
yokoku-library.workspace = true
yokoku-media.workspace = true

apalis.workspace = true
apalis-cron.workspace = true
jiff.workspace = true
jiff-cron.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
tracing-subscriber.workspace = true
