[package]
name = "yokoku-integrations"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
yokoku-domain.workspace = true
yokoku-events.workspace = true

async-trait.workspace = true
jiff.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
yokoku-db.workspace = true

tokio = { workspace = true, features = ["rt", "macros"] }
