[package]
name = "yokoku-web"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[[bin]]
name = "gallery"
path = "gallery/main.rs"

[lints]
workspace = true

[dependencies]
serde.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
topcoat = { workspace = true, features = ["default", "font-fontsource", "icon-iconify", "tailwind"] }

[build-dependencies]
topcoat = { workspace = true, features = ["icon-iconify", "tailwind"] }

[dev-dependencies]
rstest.workspace = true
