[package]
name = "yokoku-test-support"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
yokoku-core.workspace = true
yokoku-domain.workspace = true
yokoku-infra.workspace = true

jiff.workspace = true
serde_json.workspace = true
sqlx.workspace = true
wiremock.workspace = true
