[package]
name = "yokoku-test-support"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
yokoku-db.workspace = true
yokoku-domain.workspace = true
yokoku-events.workspace = true
yokoku-system.workspace = true

async-trait.workspace = true
jiff.workspace = true
serde_json.workspace = true
wiremock.workspace = true
